### ISSUE TITLE
关于嵌入B站视频的代码

### ISSUE THREAD

**Issue by Tianxiang-C** [zhanglj37/zhanglj37.github.io#1]
你好，我是你的follower，很喜欢你的主页和这篇[博客](https://lijinzhang.com/post/2022-04-15-phd-decision/)。有一个问题，就是用B站自己的代码在网页中嵌入视频的时候，显示的效果不太好（在这篇博客中也是这样）。因此，我想冒昧地建议你考虑参考这篇[博客](https://bestzuo.cn/posts/blog-bilbli.html)，修改一下嵌入B站视频的代码，优化视频嵌入的效果。如有打扰，敬请谅解。

**Comment by zhanglj37** [comment]
哇塞，感谢！已修改！
